(library
 (name links)
 (modules links))

(library
 (name omd_utils)
 (libraries links omd)
 (modules omd_utils))

(library
 (name categorize)
 (inline_tests)
 (preprocess
  (pps ppx_expect))
 (libraries links omd omd_utils)
 (modules categorize))

(library
 (name monolith)
 (libraries links categorize omd cohttp-lwt-unix lwt unix omd_utils)
 (modules monolith))
